// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverlist.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_serverlist_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_serverlist_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_serverlist_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_serverlist_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_serverlist_2eproto;
namespace TeraLauncher {
class ServerList;
struct ServerListDefaultTypeInternal;
extern ServerListDefaultTypeInternal _ServerList_default_instance_;
class ServerList_Server;
struct ServerList_ServerDefaultTypeInternal;
extern ServerList_ServerDefaultTypeInternal _ServerList_Server_default_instance_;
}  // namespace TeraLauncher
PROTOBUF_NAMESPACE_OPEN
template<> ::TeraLauncher::ServerList* Arena::CreateMaybeMessage<::TeraLauncher::ServerList>(Arena*);
template<> ::TeraLauncher::ServerList_Server* Arena::CreateMaybeMessage<::TeraLauncher::ServerList_Server>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace TeraLauncher {

// ===================================================================

class ServerList_Server final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TeraLauncher.ServerList.Server) */ {
 public:
  inline ServerList_Server() : ServerList_Server(nullptr) {}
  ~ServerList_Server() override;
  explicit PROTOBUF_CONSTEXPR ServerList_Server(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ServerList_Server(const ServerList_Server& from);
  ServerList_Server(ServerList_Server&& from) noexcept
    : ServerList_Server() {
    *this = ::std::move(from);
  }

  inline ServerList_Server& operator=(const ServerList_Server& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerList_Server& operator=(ServerList_Server&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ServerList_Server& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServerList_Server* internal_default_instance() {
    return reinterpret_cast<const ServerList_Server*>(
               &_ServerList_Server_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ServerList_Server& a, ServerList_Server& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerList_Server* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerList_Server* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ServerList_Server* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ServerList_Server>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ServerList_Server& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ServerList_Server& from) {
    ServerList_Server::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerList_Server* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TeraLauncher.ServerList.Server";
  }
  protected:
  explicit ServerList_Server(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kCategoryFieldNumber = 3,
    kTitleFieldNumber = 4,
    kQueueFieldNumber = 5,
    kPopulationFieldNumber = 6,
    kPopupFieldNumber = 10,
    kHostFieldNumber = 11,
    kIdFieldNumber = 1,
    kAddressFieldNumber = 7,
    kPortFieldNumber = 8,
    kAvailableFieldNumber = 9,
  };
  // required bytes name = 2;
  bool has_name() const;
  private:
  bool _internal_has_name() const;
  public:
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // required bytes category = 3;
  bool has_category() const;
  private:
  bool _internal_has_category() const;
  public:
  void clear_category();
  const std::string& category() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_category(ArgT0&& arg0, ArgT... args);
  std::string* mutable_category();
  PROTOBUF_NODISCARD std::string* release_category();
  void set_allocated_category(std::string* category);
  private:
  const std::string& _internal_category() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_category(const std::string& value);
  std::string* _internal_mutable_category();
  public:

  // required bytes title = 4;
  bool has_title() const;
  private:
  bool _internal_has_title() const;
  public:
  void clear_title();
  const std::string& title() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_title(ArgT0&& arg0, ArgT... args);
  std::string* mutable_title();
  PROTOBUF_NODISCARD std::string* release_title();
  void set_allocated_title(std::string* title);
  private:
  const std::string& _internal_title() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_title(const std::string& value);
  std::string* _internal_mutable_title();
  public:

  // required bytes queue = 5;
  bool has_queue() const;
  private:
  bool _internal_has_queue() const;
  public:
  void clear_queue();
  const std::string& queue() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_queue(ArgT0&& arg0, ArgT... args);
  std::string* mutable_queue();
  PROTOBUF_NODISCARD std::string* release_queue();
  void set_allocated_queue(std::string* queue);
  private:
  const std::string& _internal_queue() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_queue(const std::string& value);
  std::string* _internal_mutable_queue();
  public:

  // required bytes population = 6;
  bool has_population() const;
  private:
  bool _internal_has_population() const;
  public:
  void clear_population();
  const std::string& population() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_population(ArgT0&& arg0, ArgT... args);
  std::string* mutable_population();
  PROTOBUF_NODISCARD std::string* release_population();
  void set_allocated_population(std::string* population);
  private:
  const std::string& _internal_population() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_population(const std::string& value);
  std::string* _internal_mutable_population();
  public:

  // required bytes popup = 10;
  bool has_popup() const;
  private:
  bool _internal_has_popup() const;
  public:
  void clear_popup();
  const std::string& popup() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_popup(ArgT0&& arg0, ArgT... args);
  std::string* mutable_popup();
  PROTOBUF_NODISCARD std::string* release_popup();
  void set_allocated_popup(std::string* popup);
  private:
  const std::string& _internal_popup() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_popup(const std::string& value);
  std::string* _internal_mutable_popup();
  public:

  // optional bytes host = 11;
  bool has_host() const;
  private:
  bool _internal_has_host() const;
  public:
  void clear_host();
  const std::string& host() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_host(ArgT0&& arg0, ArgT... args);
  std::string* mutable_host();
  PROTOBUF_NODISCARD std::string* release_host();
  void set_allocated_host(std::string* host);
  private:
  const std::string& _internal_host() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_host(const std::string& value);
  std::string* _internal_mutable_host();
  public:

  // required fixed32 id = 1;
  bool has_id() const;
  private:
  bool _internal_has_id() const;
  public:
  void clear_id();
  uint32_t id() const;
  void set_id(uint32_t value);
  private:
  uint32_t _internal_id() const;
  void _internal_set_id(uint32_t value);
  public:

  // required fixed32 address = 7;
  bool has_address() const;
  private:
  bool _internal_has_address() const;
  public:
  void clear_address();
  uint32_t address() const;
  void set_address(uint32_t value);
  private:
  uint32_t _internal_address() const;
  void _internal_set_address(uint32_t value);
  public:

  // required fixed32 port = 8;
  bool has_port() const;
  private:
  bool _internal_has_port() const;
  public:
  void clear_port();
  uint32_t port() const;
  void set_port(uint32_t value);
  private:
  uint32_t _internal_port() const;
  void _internal_set_port(uint32_t value);
  public:

  // required fixed32 available = 9;
  bool has_available() const;
  private:
  bool _internal_has_available() const;
  public:
  void clear_available();
  uint32_t available() const;
  void set_available(uint32_t value);
  private:
  uint32_t _internal_available() const;
  void _internal_set_available(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:TeraLauncher.ServerList.Server)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr category_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr title_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr queue_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr population_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr popup_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr host_;
    uint32_t id_;
    uint32_t address_;
    uint32_t port_;
    uint32_t available_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_serverlist_2eproto;
};
// -------------------------------------------------------------------

class ServerList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TeraLauncher.ServerList) */ {
 public:
  inline ServerList() : ServerList(nullptr) {}
  ~ServerList() override;
  explicit PROTOBUF_CONSTEXPR ServerList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ServerList(const ServerList& from);
  ServerList(ServerList&& from) noexcept
    : ServerList() {
    *this = ::std::move(from);
  }

  inline ServerList& operator=(const ServerList& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerList& operator=(ServerList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ServerList& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServerList* internal_default_instance() {
    return reinterpret_cast<const ServerList*>(
               &_ServerList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ServerList& a, ServerList& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ServerList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ServerList>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ServerList& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ServerList& from) {
    ServerList::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerList* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TeraLauncher.ServerList";
  }
  protected:
  explicit ServerList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ServerList_Server Server;

  // accessors -------------------------------------------------------

  enum : int {
    kServersFieldNumber = 1,
    kLastServerIdFieldNumber = 2,
    kSortCriterionFieldNumber = 3,
  };
  // repeated .TeraLauncher.ServerList.Server servers = 1;
  int servers_size() const;
  private:
  int _internal_servers_size() const;
  public:
  void clear_servers();
  ::TeraLauncher::ServerList_Server* mutable_servers(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TeraLauncher::ServerList_Server >*
      mutable_servers();
  private:
  const ::TeraLauncher::ServerList_Server& _internal_servers(int index) const;
  ::TeraLauncher::ServerList_Server* _internal_add_servers();
  public:
  const ::TeraLauncher::ServerList_Server& servers(int index) const;
  ::TeraLauncher::ServerList_Server* add_servers();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TeraLauncher::ServerList_Server >&
      servers() const;

  // required fixed32 lastServerId = 2;
  bool has_lastserverid() const;
  private:
  bool _internal_has_lastserverid() const;
  public:
  void clear_lastserverid();
  uint32_t lastserverid() const;
  void set_lastserverid(uint32_t value);
  private:
  uint32_t _internal_lastserverid() const;
  void _internal_set_lastserverid(uint32_t value);
  public:

  // required fixed32 sortCriterion = 3;
  bool has_sortcriterion() const;
  private:
  bool _internal_has_sortcriterion() const;
  public:
  void clear_sortcriterion();
  uint32_t sortcriterion() const;
  void set_sortcriterion(uint32_t value);
  private:
  uint32_t _internal_sortcriterion() const;
  void _internal_set_sortcriterion(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:TeraLauncher.ServerList)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TeraLauncher::ServerList_Server > servers_;
    uint32_t lastserverid_;
    uint32_t sortcriterion_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_serverlist_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ServerList_Server

// required fixed32 id = 1;
inline bool ServerList_Server::_internal_has_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool ServerList_Server::has_id() const {
  return _internal_has_id();
}
inline void ServerList_Server::clear_id() {
  _impl_.id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline uint32_t ServerList_Server::_internal_id() const {
  return _impl_.id_;
}
inline uint32_t ServerList_Server::id() const {
  // @@protoc_insertion_point(field_get:TeraLauncher.ServerList.Server.id)
  return _internal_id();
}
inline void ServerList_Server::_internal_set_id(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.id_ = value;
}
inline void ServerList_Server::set_id(uint32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:TeraLauncher.ServerList.Server.id)
}

// required bytes name = 2;
inline bool ServerList_Server::_internal_has_name() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ServerList_Server::has_name() const {
  return _internal_has_name();
}
inline void ServerList_Server::clear_name() {
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ServerList_Server::name() const {
  // @@protoc_insertion_point(field_get:TeraLauncher.ServerList.Server.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ServerList_Server::set_name(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.name_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:TeraLauncher.ServerList.Server.name)
}
inline std::string* ServerList_Server::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:TeraLauncher.ServerList.Server.name)
  return _s;
}
inline const std::string& ServerList_Server::_internal_name() const {
  return _impl_.name_.Get();
}
inline void ServerList_Server::_internal_set_name(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* ServerList_Server::_internal_mutable_name() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* ServerList_Server::release_name() {
  // @@protoc_insertion_point(field_release:TeraLauncher.ServerList.Server.name)
  if (!_internal_has_name()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.name_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ServerList_Server::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TeraLauncher.ServerList.Server.name)
}

// required bytes category = 3;
inline bool ServerList_Server::_internal_has_category() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool ServerList_Server::has_category() const {
  return _internal_has_category();
}
inline void ServerList_Server::clear_category() {
  _impl_.category_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ServerList_Server::category() const {
  // @@protoc_insertion_point(field_get:TeraLauncher.ServerList.Server.category)
  return _internal_category();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ServerList_Server::set_category(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.category_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:TeraLauncher.ServerList.Server.category)
}
inline std::string* ServerList_Server::mutable_category() {
  std::string* _s = _internal_mutable_category();
  // @@protoc_insertion_point(field_mutable:TeraLauncher.ServerList.Server.category)
  return _s;
}
inline const std::string& ServerList_Server::_internal_category() const {
  return _impl_.category_.Get();
}
inline void ServerList_Server::_internal_set_category(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.category_.Set(value, GetArenaForAllocation());
}
inline std::string* ServerList_Server::_internal_mutable_category() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.category_.Mutable(GetArenaForAllocation());
}
inline std::string* ServerList_Server::release_category() {
  // @@protoc_insertion_point(field_release:TeraLauncher.ServerList.Server.category)
  if (!_internal_has_category()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.category_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.category_.IsDefault()) {
    _impl_.category_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ServerList_Server::set_allocated_category(std::string* category) {
  if (category != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.category_.SetAllocated(category, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.category_.IsDefault()) {
    _impl_.category_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TeraLauncher.ServerList.Server.category)
}

// required bytes title = 4;
inline bool ServerList_Server::_internal_has_title() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool ServerList_Server::has_title() const {
  return _internal_has_title();
}
inline void ServerList_Server::clear_title() {
  _impl_.title_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& ServerList_Server::title() const {
  // @@protoc_insertion_point(field_get:TeraLauncher.ServerList.Server.title)
  return _internal_title();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ServerList_Server::set_title(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000004u;
 _impl_.title_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:TeraLauncher.ServerList.Server.title)
}
inline std::string* ServerList_Server::mutable_title() {
  std::string* _s = _internal_mutable_title();
  // @@protoc_insertion_point(field_mutable:TeraLauncher.ServerList.Server.title)
  return _s;
}
inline const std::string& ServerList_Server::_internal_title() const {
  return _impl_.title_.Get();
}
inline void ServerList_Server::_internal_set_title(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.title_.Set(value, GetArenaForAllocation());
}
inline std::string* ServerList_Server::_internal_mutable_title() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.title_.Mutable(GetArenaForAllocation());
}
inline std::string* ServerList_Server::release_title() {
  // @@protoc_insertion_point(field_release:TeraLauncher.ServerList.Server.title)
  if (!_internal_has_title()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* p = _impl_.title_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.title_.IsDefault()) {
    _impl_.title_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ServerList_Server::set_allocated_title(std::string* title) {
  if (title != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.title_.SetAllocated(title, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.title_.IsDefault()) {
    _impl_.title_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TeraLauncher.ServerList.Server.title)
}

// required bytes queue = 5;
inline bool ServerList_Server::_internal_has_queue() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool ServerList_Server::has_queue() const {
  return _internal_has_queue();
}
inline void ServerList_Server::clear_queue() {
  _impl_.queue_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& ServerList_Server::queue() const {
  // @@protoc_insertion_point(field_get:TeraLauncher.ServerList.Server.queue)
  return _internal_queue();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ServerList_Server::set_queue(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000008u;
 _impl_.queue_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:TeraLauncher.ServerList.Server.queue)
}
inline std::string* ServerList_Server::mutable_queue() {
  std::string* _s = _internal_mutable_queue();
  // @@protoc_insertion_point(field_mutable:TeraLauncher.ServerList.Server.queue)
  return _s;
}
inline const std::string& ServerList_Server::_internal_queue() const {
  return _impl_.queue_.Get();
}
inline void ServerList_Server::_internal_set_queue(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.queue_.Set(value, GetArenaForAllocation());
}
inline std::string* ServerList_Server::_internal_mutable_queue() {
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.queue_.Mutable(GetArenaForAllocation());
}
inline std::string* ServerList_Server::release_queue() {
  // @@protoc_insertion_point(field_release:TeraLauncher.ServerList.Server.queue)
  if (!_internal_has_queue()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* p = _impl_.queue_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.queue_.IsDefault()) {
    _impl_.queue_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ServerList_Server::set_allocated_queue(std::string* queue) {
  if (queue != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.queue_.SetAllocated(queue, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.queue_.IsDefault()) {
    _impl_.queue_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TeraLauncher.ServerList.Server.queue)
}

// required bytes population = 6;
inline bool ServerList_Server::_internal_has_population() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool ServerList_Server::has_population() const {
  return _internal_has_population();
}
inline void ServerList_Server::clear_population() {
  _impl_.population_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const std::string& ServerList_Server::population() const {
  // @@protoc_insertion_point(field_get:TeraLauncher.ServerList.Server.population)
  return _internal_population();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ServerList_Server::set_population(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000010u;
 _impl_.population_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:TeraLauncher.ServerList.Server.population)
}
inline std::string* ServerList_Server::mutable_population() {
  std::string* _s = _internal_mutable_population();
  // @@protoc_insertion_point(field_mutable:TeraLauncher.ServerList.Server.population)
  return _s;
}
inline const std::string& ServerList_Server::_internal_population() const {
  return _impl_.population_.Get();
}
inline void ServerList_Server::_internal_set_population(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.population_.Set(value, GetArenaForAllocation());
}
inline std::string* ServerList_Server::_internal_mutable_population() {
  _impl_._has_bits_[0] |= 0x00000010u;
  return _impl_.population_.Mutable(GetArenaForAllocation());
}
inline std::string* ServerList_Server::release_population() {
  // @@protoc_insertion_point(field_release:TeraLauncher.ServerList.Server.population)
  if (!_internal_has_population()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000010u;
  auto* p = _impl_.population_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.population_.IsDefault()) {
    _impl_.population_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ServerList_Server::set_allocated_population(std::string* population) {
  if (population != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  _impl_.population_.SetAllocated(population, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.population_.IsDefault()) {
    _impl_.population_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TeraLauncher.ServerList.Server.population)
}

// required fixed32 address = 7;
inline bool ServerList_Server::_internal_has_address() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool ServerList_Server::has_address() const {
  return _internal_has_address();
}
inline void ServerList_Server::clear_address() {
  _impl_.address_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline uint32_t ServerList_Server::_internal_address() const {
  return _impl_.address_;
}
inline uint32_t ServerList_Server::address() const {
  // @@protoc_insertion_point(field_get:TeraLauncher.ServerList.Server.address)
  return _internal_address();
}
inline void ServerList_Server::_internal_set_address(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000100u;
  _impl_.address_ = value;
}
inline void ServerList_Server::set_address(uint32_t value) {
  _internal_set_address(value);
  // @@protoc_insertion_point(field_set:TeraLauncher.ServerList.Server.address)
}

// required fixed32 port = 8;
inline bool ServerList_Server::_internal_has_port() const {
  bool value = (_impl_._has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool ServerList_Server::has_port() const {
  return _internal_has_port();
}
inline void ServerList_Server::clear_port() {
  _impl_.port_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline uint32_t ServerList_Server::_internal_port() const {
  return _impl_.port_;
}
inline uint32_t ServerList_Server::port() const {
  // @@protoc_insertion_point(field_get:TeraLauncher.ServerList.Server.port)
  return _internal_port();
}
inline void ServerList_Server::_internal_set_port(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000200u;
  _impl_.port_ = value;
}
inline void ServerList_Server::set_port(uint32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:TeraLauncher.ServerList.Server.port)
}

// required fixed32 available = 9;
inline bool ServerList_Server::_internal_has_available() const {
  bool value = (_impl_._has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool ServerList_Server::has_available() const {
  return _internal_has_available();
}
inline void ServerList_Server::clear_available() {
  _impl_.available_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000400u;
}
inline uint32_t ServerList_Server::_internal_available() const {
  return _impl_.available_;
}
inline uint32_t ServerList_Server::available() const {
  // @@protoc_insertion_point(field_get:TeraLauncher.ServerList.Server.available)
  return _internal_available();
}
inline void ServerList_Server::_internal_set_available(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000400u;
  _impl_.available_ = value;
}
inline void ServerList_Server::set_available(uint32_t value) {
  _internal_set_available(value);
  // @@protoc_insertion_point(field_set:TeraLauncher.ServerList.Server.available)
}

// required bytes popup = 10;
inline bool ServerList_Server::_internal_has_popup() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool ServerList_Server::has_popup() const {
  return _internal_has_popup();
}
inline void ServerList_Server::clear_popup() {
  _impl_.popup_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline const std::string& ServerList_Server::popup() const {
  // @@protoc_insertion_point(field_get:TeraLauncher.ServerList.Server.popup)
  return _internal_popup();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ServerList_Server::set_popup(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000020u;
 _impl_.popup_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:TeraLauncher.ServerList.Server.popup)
}
inline std::string* ServerList_Server::mutable_popup() {
  std::string* _s = _internal_mutable_popup();
  // @@protoc_insertion_point(field_mutable:TeraLauncher.ServerList.Server.popup)
  return _s;
}
inline const std::string& ServerList_Server::_internal_popup() const {
  return _impl_.popup_.Get();
}
inline void ServerList_Server::_internal_set_popup(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.popup_.Set(value, GetArenaForAllocation());
}
inline std::string* ServerList_Server::_internal_mutable_popup() {
  _impl_._has_bits_[0] |= 0x00000020u;
  return _impl_.popup_.Mutable(GetArenaForAllocation());
}
inline std::string* ServerList_Server::release_popup() {
  // @@protoc_insertion_point(field_release:TeraLauncher.ServerList.Server.popup)
  if (!_internal_has_popup()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000020u;
  auto* p = _impl_.popup_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.popup_.IsDefault()) {
    _impl_.popup_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ServerList_Server::set_allocated_popup(std::string* popup) {
  if (popup != nullptr) {
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  _impl_.popup_.SetAllocated(popup, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.popup_.IsDefault()) {
    _impl_.popup_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TeraLauncher.ServerList.Server.popup)
}

// optional bytes host = 11;
inline bool ServerList_Server::_internal_has_host() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool ServerList_Server::has_host() const {
  return _internal_has_host();
}
inline void ServerList_Server::clear_host() {
  _impl_.host_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline const std::string& ServerList_Server::host() const {
  // @@protoc_insertion_point(field_get:TeraLauncher.ServerList.Server.host)
  return _internal_host();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ServerList_Server::set_host(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000040u;
 _impl_.host_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:TeraLauncher.ServerList.Server.host)
}
inline std::string* ServerList_Server::mutable_host() {
  std::string* _s = _internal_mutable_host();
  // @@protoc_insertion_point(field_mutable:TeraLauncher.ServerList.Server.host)
  return _s;
}
inline const std::string& ServerList_Server::_internal_host() const {
  return _impl_.host_.Get();
}
inline void ServerList_Server::_internal_set_host(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.host_.Set(value, GetArenaForAllocation());
}
inline std::string* ServerList_Server::_internal_mutable_host() {
  _impl_._has_bits_[0] |= 0x00000040u;
  return _impl_.host_.Mutable(GetArenaForAllocation());
}
inline std::string* ServerList_Server::release_host() {
  // @@protoc_insertion_point(field_release:TeraLauncher.ServerList.Server.host)
  if (!_internal_has_host()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000040u;
  auto* p = _impl_.host_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.host_.IsDefault()) {
    _impl_.host_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ServerList_Server::set_allocated_host(std::string* host) {
  if (host != nullptr) {
    _impl_._has_bits_[0] |= 0x00000040u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000040u;
  }
  _impl_.host_.SetAllocated(host, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.host_.IsDefault()) {
    _impl_.host_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TeraLauncher.ServerList.Server.host)
}

// -------------------------------------------------------------------

// ServerList

// repeated .TeraLauncher.ServerList.Server servers = 1;
inline int ServerList::_internal_servers_size() const {
  return _impl_.servers_.size();
}
inline int ServerList::servers_size() const {
  return _internal_servers_size();
}
inline void ServerList::clear_servers() {
  _impl_.servers_.Clear();
}
inline ::TeraLauncher::ServerList_Server* ServerList::mutable_servers(int index) {
  // @@protoc_insertion_point(field_mutable:TeraLauncher.ServerList.servers)
  return _impl_.servers_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TeraLauncher::ServerList_Server >*
ServerList::mutable_servers() {
  // @@protoc_insertion_point(field_mutable_list:TeraLauncher.ServerList.servers)
  return &_impl_.servers_;
}
inline const ::TeraLauncher::ServerList_Server& ServerList::_internal_servers(int index) const {
  return _impl_.servers_.Get(index);
}
inline const ::TeraLauncher::ServerList_Server& ServerList::servers(int index) const {
  // @@protoc_insertion_point(field_get:TeraLauncher.ServerList.servers)
  return _internal_servers(index);
}
inline ::TeraLauncher::ServerList_Server* ServerList::_internal_add_servers() {
  return _impl_.servers_.Add();
}
inline ::TeraLauncher::ServerList_Server* ServerList::add_servers() {
  ::TeraLauncher::ServerList_Server* _add = _internal_add_servers();
  // @@protoc_insertion_point(field_add:TeraLauncher.ServerList.servers)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TeraLauncher::ServerList_Server >&
ServerList::servers() const {
  // @@protoc_insertion_point(field_list:TeraLauncher.ServerList.servers)
  return _impl_.servers_;
}

// required fixed32 lastServerId = 2;
inline bool ServerList::_internal_has_lastserverid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ServerList::has_lastserverid() const {
  return _internal_has_lastserverid();
}
inline void ServerList::clear_lastserverid() {
  _impl_.lastserverid_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t ServerList::_internal_lastserverid() const {
  return _impl_.lastserverid_;
}
inline uint32_t ServerList::lastserverid() const {
  // @@protoc_insertion_point(field_get:TeraLauncher.ServerList.lastServerId)
  return _internal_lastserverid();
}
inline void ServerList::_internal_set_lastserverid(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.lastserverid_ = value;
}
inline void ServerList::set_lastserverid(uint32_t value) {
  _internal_set_lastserverid(value);
  // @@protoc_insertion_point(field_set:TeraLauncher.ServerList.lastServerId)
}

// required fixed32 sortCriterion = 3;
inline bool ServerList::_internal_has_sortcriterion() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool ServerList::has_sortcriterion() const {
  return _internal_has_sortcriterion();
}
inline void ServerList::clear_sortcriterion() {
  _impl_.sortcriterion_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t ServerList::_internal_sortcriterion() const {
  return _impl_.sortcriterion_;
}
inline uint32_t ServerList::sortcriterion() const {
  // @@protoc_insertion_point(field_get:TeraLauncher.ServerList.sortCriterion)
  return _internal_sortcriterion();
}
inline void ServerList::_internal_set_sortcriterion(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.sortcriterion_ = value;
}
inline void ServerList::set_sortcriterion(uint32_t value) {
  _internal_set_sortcriterion(value);
  // @@protoc_insertion_point(field_set:TeraLauncher.ServerList.sortCriterion)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace TeraLauncher

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_serverlist_2eproto
